[package]
name = "acbidder_database"
version = "0.1.0"
authors = ["Kmoneal <kmacjoneal@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["mysql"] }
dotenv = "0.9.0"
web3 = "0.1.0"
tiny-keccak = "1.3"